# -*- coding: utf-8 -*-
# P15-B leaf tasks (Deliver bullets §18.2) + per-milestone DoD.
from leafgen import mk
BEADS = []
Q = ["phase-1-5", "qualification"]

BEADS += mk("P15-B1", Q + ["eval", "testing"], "§2.3–2.6, §16.4, §18.2 P15-B1", "P15_B_QUALIFICATION_CORE_REQUIRED", "TRUST-BATTERY",
 deliver=[
  ("1", "Four case-class schemas",
   "Define the `conformance`, `safety_invariant`, `outcome_quality`, and `operability` BatteryCase schemas (criticality release_required/sampled/advisory; archetype/repo base; role-safe case ref; policy bundle; sample policy)."),
  ("2", "Trace-assertion language",
   "Implement the trace-assertion language — `never`/`always`/`eventually`/bounded-count predicates over canonical events + effect receipts — so a run that read a hidden oracle and was later policy-blocked still fails a safety invariant even when the terminal outcome looks safe."),
  ("3", "Role-safe / scorer-only fixture split",
   "Build the secure evaluation store: scorer-only trap/holdout/oracle/known-good metadata is `restricted_evaluation`-labelled and physically separated from role-safe case views; a fixture-leakage scanner runs before sealing any role-visible prompt/projection/Cassette/export."),
  ("4", "Archetype/trap corpus + poison pill",
   "Author the corpus (≥2 repos: a disposable Battery repo + a Conveyor-adjacent repo), one case per work archetype plus traps (test-weakening, impossible-contract, prompt-injection, silent-breakage, policy-evasion, hidden-oracle-access, stale-worker, ambiguous-failure) and the runner poison pill (`trap_runner_honesty`), with rotating held-out groups and near-duplicate/randomized variants."),
  ("5", "Predeclared versioned SamplingPolicy",
   "Implement the content-addressed `SamplingPolicy` (method, min/max samples, confidence, floor, stopping rule, sampling unit = repository case cluster, per-cluster cap, strata) frozen before any live call; a threshold/stop-rule change requires a new policy digest."),
  ("6", "BatteryRun/SampleResult/CaseResult scorer",
   "Implement `Conveyor.Jobs.RunBattery`: resolve corpus/policy/grant/role-view digests, validate every fixture before any agent call, materialize repos at frozen bases, drive the Phase-1 loop sequentially, evaluate terminal outcomes + every trace assertion, seal one Cassette per eligible live sample, separate provider/infra failures from quality, and emit immutable per-sample/per-case/aggregate results."),
 ],
 accept=[
  "fixture validation precedes provider calls",
  "poison pill yields `battery_fixture_failure` with fixture diagnostics",
  "safety-trajectory violations are detected even when the terminal outcome is safe",
  "failed samples cannot be omitted/replaced",
  "scorer-only metadata never reaches RoleViews/prompts/workspaces/projections",
  "threshold/stop-rule change creates a new policy digest",
  "provider/infra failures are separated from quality",
 ])

BEADS += mk("P15-B2", Q + ["adapter", "tracer-required"], "§2.7, §13.3, §18.2 P15-B2", "P15_B_QUALIFICATION_CORE_REQUIRED", "ADAPTER-QUALIFICATION",
 deliver=[
  ("1", "Primary live adapter under normalized AgentRunner",
   "Implement the primary live adapter behind the normalized `AgentRunner` so the conductor independently captures PatchSet/effects/verdict and consumes causal events sufficient for replay/diagnosis; the core hardcodes no vendor."),
  ("2", "AgentRunner.MockDegraded — every capability-mismatch branch",
   "Build the deterministic `AgentRunner.MockDegraded`, the build-gating abstraction test, exercising observe-only pre-exec policy, absent/delayed cancellation, no diff capture, no cost reporting, malformed/out-of-order/duplicate events, partial tool-result capture, timeout/disconnect, and capability drift between probe and run."),
  ("3", "Adapter conformance fixtures",
   "Author cancellation, timeout, malformed/out-of-order/duplicate-event, crash, and credential-revocation fixtures; malformed/missing events must fail closed."),
  ("4", "Capability-to-autonomy policy + EffectiveCapabilitySet",
   "Implement `CapabilityClaim` (declared/probed/observed) and the derived `EffectiveCapabilitySet` (intersection of declaration, probes, observed behaviour, health, policy); the conductor derives max autonomy from it + policy + a valid AdmissionPermit, never from an adapter name."),
  ("5", "Adapter health probe/circuit integration",
   "Integrate adapter health probes + circuit so an open circuit is ineligible for new attempts, capability drift fences adapter output + suspends new permits + creates a QualificationImpact, and a transient outage suspends execution without rewriting historical evidence."),
 ],
 accept=[
  "the conductor independently captures PatchSet/effects/verdict",
  "malformed/missing events fail closed",
  "requested autonomy is no higher than actual capability",
  "MockDegraded hits all mismatch branches",
  "provider/vendor code does not fork the conductor state machine",
  "an open circuit blocks new attempts and affects grants",
 ])

BEADS += mk("P15-B3", Q + ["evidence"], "§2.9, §5.3, §16.4, §18.2 P15-B3", "P15_B_QUALIFICATION_CORE_REQUIRED", "AGENT-CASSETTES",
 deliver=[
  ("1", "CassetteSeries/recordings + redaction/seal rules",
   "Implement `CassetteSeries` (one generation surface per role/spec/adapter) + immutable `AgentCassette` recordings with seal_status and provider-identity-confidence (exact/declared_only/family_only/unknown); redaction + integrity checks precede sealing."),
  ("2", "Normalized causal transcript + tool records",
   "Record canonical transcript events with per-stream sequence + happens-before edges, and tool transcripts (normalized args, ToolContract key, policy decision, result/error, idempotency key, effect receipt, causal linkage); store observable output only, never hidden chain-of-thought."),
  ("3", "Full / hybrid / proposal / compatible replay modes",
   "Implement `replay_full` (causal partial order + exact replayable tool args under virtual clock), `replay_hybrid` (rerun current deterministic gates/obligations over recorded output — the hard regression mode), `replay_proposal` (planning proposal through current passes), and `replay_compatible` (dev-only, never a trust gate)."),
  ("4", "Virtual clock + deterministic ID allocator",
   "Provide the virtual clock + deterministic ID allocator and the `NondeterminismLedger` (clock reads, RNG seeds, env reads, external-read versions, tool-equivalence policy versions); an incomplete required ledger returns `replay_incomplete`, not success."),
  ("5", "Generation vs evaluation surface digests",
   "Compute the generation-freshness digest (everything the agent observed/that shaped its tool loop) and the evaluation surface; a generation-surface change misses every replay mode, while a gate/test/eval-only change stays eligible for hybrid replay."),
  ("6", "Strict-replay divergence diagnostics",
   "Implement strict-replay divergence diagnostics that fail when the conductor requests a different replayable tool, different normalized args, or a different causal sequence."),
  ("7", "Content-addressed ReplayAnchorSet policy + fixtures",
   "Implement the `ReplayAnchorSet` selected by policy BEFORE the evaluated change, including representative successful/failed/disputed/safety-sensitive recordings + the exact expected replay assertions; a failed live quality sample may be a valuable conductor-failure anchor."),
 ],
 accept=[
  "repeated live samples create separate recordings",
  "generation-surface changes miss every replay mode",
  "gate/test/evaluation-only changes remain eligible for hybrid replay",
  "strict replay rejects different tool args/order",
  "full replay reproduces the conductor projection",
  "hybrid replay reruns current gates/obligations",
  "compatible replay never satisfies a trust gate",
  "anchor selection is frozen before the evaluated change and includes success, failure/dispute, and safety-sensitive trajectories",
  "recorded gate claims never become authority",
 ])

BEADS += mk("P15-B4", Q + ["testing", "trust-required"], "§2.10, §5.3, §18.2 P15-B4", "P15_B_QUALIFICATION_CORE_REQUIRED + trust-required", "TEST-INTEGRITY",
 deliver=[
  ("1", "Obligation / evidence / waiver resources",
   "Implement `VerificationObligation` (example/property/interface/differential/metamorphic/policy/human_judgment), `VerificationEvidence` (10 evidence kinds + validity), and `VerificationWaiver` (human decision, compensating controls, max autonomy, owner, expiry)."),
  ("2", "Per-dimension EvidenceRequirement + ObligationSatisfaction",
   "Implement the typed per-dimension `EvidenceRequirement` predicate (specification/base_calibration/harness/candidate/hermeticity/repeatability/adversarial/mutation/human/environment) and deterministic `ObligationSatisfaction`; there is no generic 'stage at or above' rule."),
  ("3", "Integrity Sentinel probes",
   "Implement the Test-Integrity Sentinel: role-appropriate base calibration, red-on-stub/falsifier survival, hermeticity (network/clock/RNG/order/locale/shared-state), repeatability, obligation/AC/interface-oracle mapping, mount/write-boundary, required result artifacts, no production-source mutation, no hidden secret/network, falsifier preservation — verdicts trustworthy/suspect/untrustworthy/not_assessed."),
  ("4", "Quarantine lifecycle (no authority laundering)",
   "Implement `TestQuarantine` (flaky/non_hermetic/vacuous/order_dependent/infrastructure_sensitive) that isolates a suspect test but NEVER marks an obligation satisfied; a required obligation stays blocked until a valid replacement oracle or an explicit scoped expiring waiver exists."),
  ("5", "Compiler-falsifier placeholder seam",
   "Add the compiler-derived-falsifier placeholder seam so Phase-2 falsifier seeds have a preservation/supersession hook in the obligation model."),
  ("6", "Obligation/waiver Cockpit projection",
   "Build the obligation/waiver Cockpit projection (coverage, invalid evidence, waivers, owners, expiry)."),
 ],
 accept=[
  "readiness is per obligation, not TestPack aggregate",
  "required flake/non-hermetic/vacuity blocks",
  "quarantine cannot satisfy an obligation",
  "an active waiver requires human decision, owner, expiry, controls, max autonomy",
  "human-observed evidence is distinct from machine evidence",
  "repeated TestIntegrityRun samples are permitted and comparable",
 ])

BEADS += mk("P15-B5", Q + ["canary", "eval"], "§2.11, §2.14, §16.5, §18.2 P15-B5", "P15_B_QUALIFICATION_CORE_REQUIRED + trust-required", "BEHAVIOR-LOCK (seed)",
 deliver=[
  ("1", "Gate mutants by archetype",
   "Grow the gate-mutant canary corpus by archetype; every mutant declares an expected failing stage + stable reason, and known-good controls pass the same path."),
  ("2", "Trust-tool canaries + clean boundaries",
   "Author catch canaries + clean false-positive boundaries for every trust tool (policy bypass, fencing stale-epoch, role visibility, replay freshness, approval binding, emergency stop, global budget, evidence comparator, diagnosis, interrogator, cassette freshness, summary completeness) — see spec_canaries.py for the individual meta-canary beads."),
  ("3", "Bounded BehaviorOracleAdapter (refactor fixture)",
   "Implement ONE bounded `BehaviorOracleAdapter` for the refactor fixture: run base+candidate on identical bounded inputs, normalize declared nondeterminism, compare observable output/state, report `no_divergence_observed`/`diverged`/`inconclusive` — never a proof of general equivalence (broad engine = Phase 4)."),
  ("4", "Clean controls for every trust tool",
   "Provide the clean-control fixtures (valid fixture runnable, clean deterministic evidence trusted, authorized action allowed, cosmetic-only change cosmetic, allowed normalized variation passes, benign repo prose stays data)."),
 ],
 accept=[
  "every trust tool catches its planted defect and passes its clean boundary",
  "behavior drift is detected; a genuine refactor passes",
  "the result is `no_divergence_observed`, not a general proof",
  "one meta-canary miss blocks the affected grant",
  "the release report includes all failed/excluded cases",
 ])

BEADS += mk("P15-B6", Q + ["cli", "evidence"], "§2.12–2.13, §12, §18.2 P15-B6, §28 Workstream D", "P15_B_QUALIFICATION_CORE_REQUIRED", "EVIDENCE-FORENSICS, FAILURE-DIAGNOSIS",
 deliver=[
  ("1", "Canonical multi-label comparator",
   "Implement the typed comparator over the canonical materiality vocabulary (identical/cosmetic/context_only/evidence_changing/scope_*/contract_changing/acceptance_*/policy_*/environment_changing/capability_changing/approval_changing/grant_changing/incomparable) with a deterministic precedence rule; missing/unauthorized/erased/digest-mismatched subjects yield `incomparable`."),
  ("2", "Evidence Time Machine CLI commands",
   "Implement `why_stale`, `why_different`, and `diff_runs/diff_plans/diff_candidates/diff_artifacts/diff_grants` (canonical JSON + optional Markdown), comparing across grants/specs/RoleViews/contracts/obligations/tests/context/patches/gate-stages/effect-receipts/roots/lineage."),
  ("3", "Immutable FailureDiagnosis",
   "Implement the immutable deterministic-first `FailureDiagnosis` (primary classification + contributing factors + observations + competing hypotheses + confidence basis + abstention) consuming structured station errors/gate stages/evidence/policy/receipts/budgets/replay-divergence/lease state before any agent."),
  ("4", "RecoveryProposal + RecoveryAction + action registry",
   "Implement `RecoveryProposal` (typed action_key, reusable/invalidated artifacts, new-spec/attempt + human/policy preconditions) and separately-authorized `RecoveryAction`; CLI/UI are projections of action_key + validated arguments, never raw shell."),
  ("5", "Safe-auto-action policy + honesty eval",
   "Implement the safe-automatic-action policy (only deterministic-precondition + fenced + grant-admitted + budgeted + idempotent + bounded-retry actions auto-apply) and the diagnosis/recovery honesty eval (per-class precision/recall, abstention appropriateness, harmful-action rate, reconciliation correctness, invalidation accuracy)."),
  ("6", "Invalidation / impact-preview kernel",
   "Implement the `preview_invalidation` kernel computed from ArtifactInput / interface bindings / decision blocks / obligations / approval roots, failing wide when impact confidence is low."),
 ],
 accept=[
  "weakening/freshness/root/grant changes classify materially",
  "missing/erased/tampered evidence yields `incomparable`",
  "the ambiguous fixture abstains",
  "diagnosis remains immutable",
  "semantic recovery requires normal authority",
  "safe actions are idempotent, fenced, budgeted, and grant-admitted",
  "raw shell commands are not authoritative recovery data",
 ])

BEADS += mk("P15-B7", Q + ["eval"], "§2.15–2.16, §16.6–16.9, §17.2, §18.2 P15-B7", "measurement-only / should-have (§19)", "TRUST-BATTERY (live)",
 deliver=[
  ("1", "Live predeclared samples for requested scopes",
   "Execute live predeclared samples for the requested grant-scope strata through the frozen `SamplingPolicy`; one live miss changes the band, it does NOT create a rerun-until-green gate."),
  ("2", "Success bands + sample-size reporting",
   "Report p_low/p_high/confidence/sample_count/quality_floor/worst_required_stratum_result + provider/infra-failure counts; insufficient samples are `not_assessed`, never pass; safety failures are never averaged away."),
  ("3", "Optional secondary live adapter representative set",
   "Optionally run a second materially-different live adapter on a representative set selected IN ADVANCE — confirmation of the abstraction, never the core build oracle; a secondary outage doesn't invalidate the deterministic build."),
  ("4", "Scout/AGENTS/prompt/adapter ablations",
   "Run controlled measurement studies (Scout, AGENTS.md, prompt versions, adapters) against frozen inputs; retain null/negative results."),
  ("5", "Context-ground-truth fixtures + proxies",
   "Provide `ContextGroundTruth` fixtures (necessary/useful/forbidden refs) for labelled precision/recall, and the explicit proxy metrics (selected_context_used_by_patch, files_opened_but_unused, post_failure_missing_context, budget_exhausted, critical_context_shed) for unlabelled work."),
  ("6", "Optional Tutor / retry-escalation shadows",
   "Optionally run Tutor (advisory, cannot close a Slice/satisfy an obligation) and retry-with-escalation shadows (new attempt with next profile for implementation/validation failures; never consumes a tier for contract/policy/adapter/infra faults)."),
 ],
 accept=[
  "no rerun-until-green binary live gate",
  "statistical method/threshold/budget frozen before samples",
  "insufficient evidence remains not assessed",
  "safety failure cannot be averaged away",
  "secondary-provider outage does not invalidate the core deterministic build",
  "null/negative studies are retained",
  "Tutor cannot close work; contract/policy faults do not consume escalation",
 ])

BEADS += mk("P15-B8", Q + ["gate", "tracer-required"], "§0.3, §2.8, §2.17, §14.1, §17.1–17.2, §18.2 P15-B8", "P15_B_QUALIFICATION_CORE_REQUIRED", "QUALIFICATION-GRANTS",
 deliver=[
  ("1", "Run all hard blockers + live sample policies",
   "Implement `mix conveyor.qualification_gate PROJECT_ID --scope`: validate registry/canonicalization/attestations/derivation/policy/scope; require all deterministic conformance + safety trace assertions + canaries/meta-canaries/poison-pill/fencing/RoleView/hidden-oracle/integrity + strict/full/hybrid replay to pass; evaluate live samples through the frozen statistical policy."),
  ("2", "Issue / narrow / deny QualificationGrants",
   "Implement `QualificationGrant` issuance with the `QualificationScopeLattice` (direct/inherited/supporting evidence; worst_required_stratum_result), `AdmissionPermit` + `PermitCheckpoint`, expiry/invalidation triggers; emit the narrowest grant supported by evidence and fail the command if it doesn't cover the requested scope."),
  ("3", "Publish evidence roots, limitations, expiry, residual risks",
   "Publish each grant's deterministic evidence root, live quality interval + sample count, limitations + unassessed capabilities, active waivers + compensating controls, issue/expiry timestamps, and invalidation triggers."),
  ("4", "Offline-verifiable qualification bundle",
   "Implement `qualification_bundle` + `qualification_bundle_verify --offline` validating registry/canonicalization/grant-scope/evidence-root/RootManifest/run digests/hard-invariant verdicts/canaries/replay-anchors/waivers/availability/signature-status without the live DB."),
  ("5", "Update PhaseNextDecision + authorize-or-harden",
   "Update `PhaseNextDecision` and either authorize the requested P2 scope or open a targeted hardening branch if the grant scope is insufficient."),
 ],
 accept=[
  "requested scope is machine-readable and compared with the issued scope",
  "no failed case/sample is omitted",
  "every waiver has owner/expiry/control/autonomy effect",
  "the grant is bound to adapter/profile/archetype/environment/policy/verification",
  "a broader requested scope fails if only a narrow grant is supported",
  "`qualification_gate` is reproducible from immutable evidence",
 ])
