# -*- coding: utf-8 -*-
# ~65 domain resources (§5) as first-class schema beads under their owning milestone.
# Each inherits its milestone's blockers. Delivery status per §5.11.
import spec_core
_MS = {b["label"]: b for b in spec_core.BEADS}

def _phase(ms):
    return "phase-1-5" if ms.startswith("P15") else "phase-2"

def s(name, ms, delivery, purpose, fields, ref):
    p = _MS[ms]
    return dict(
        label=f"SCHEMA-{name}", title=f"Schema: {name} ({delivery})",
        type="task", parent=ms, deps=list(p.get("deps", [])), priority=2,
        labels=[_phase(ms), "schema", delivery],
        desc=(f"# Resource `{name}`\n\n"
              f"**Purpose.** {purpose}\n\n"
              f"**Key fields.** {fields}\n\n"
              f"**Delivery.** {delivery.replace('-', ' ')} (§5.11). **Owning milestone.** {p['title']}.\n\n"
              f"**Refs.** {ref}."),
    )

# delivery: engine-now | seam-now | reuse-extend
R = [
 # ── §5.1 canonical value types (P15-A1) ──
 ("DigestRef","P15-A1","engine-now","Algorithm-agile content digest used everywhere instead of bare *_sha256.","algorithm; value","§5.1"),
 ("ResourceRef","P15-A1","seam-now","Canonical typed reference to any authority/evidence/policy object; digest⇒immutable, no-digest⇒mutable locator that cannot grant authority.","kind; id_or_key; version?; digest?; project_id?; trust_domain_id?","§5.1"),
 ("SubjectRef","P15-A1","seam-now","Policy/evidence subset of ResourceRef used as the subject of a decision/approval/comparison/effect/diagnosis/derivation; no bespoke *_id+*_kind pairs.","(subset of ResourceRef)","§5.1"),
 ("SchemaRegistryEntry","P15-A1","engine-now","Registry record fixing schema identity/version/digest/compatibility so writers emit current and readers declare supported versions.","schema_key/id/version/digest; dialect; canonicalization_profile; compatibility; reader_support[]; writer_status; migration_from[]; owner","§5.1"),
 ("AttestationStatement","P15-A1","engine-now","in-toto Statement envelope wrapping authoritative evidence, with optional DSSE signature ladder.","_type; subject[]; predicateType; predicate; signature_status; verification_bundle_ref?; signer_identity?","§5.1"),
 ("LifecycleContract","P15-A1","engine-now","Declarative lifecycle for every Tier-1 mutable-status resource; generated transition wrappers validate preconditions/lease/permit/control-gen/policy/event in one transaction so status can't bypass policy.","resource_kind; states[]; terminal_states[]; transition_key; from/to_state; required_policy_decision_keys[]; required_authority_inputs[]; required_event_type; idempotency_key_shape?; forbidden_when[]","§5.1"),
 ("RootManifest","P15-A1","engine-now","Canonical domain-separated manifest from which every authority/review/archive/evidence root is computed so a root can't be confused across kinds or omit a subject class.","root_kind; root_version; canonicalization_profile; hash_algorithm; sorted_entries[]; omitted_subject_classes[]; manifest_digest","§5.1, §7 P2-S16"),

 # ── §5.2 Shared Evidence Kernel resources ──
 ("PolicyBundle","P15-A2","engine-now","Versioned validated policy bundle; cannot activate until input schemas/conflicts/default-deny/reason-codes/bypass-canaries pass.","policy_bundle_key; version; policy_ref/digest; input_schema_refs[]; validation_report_ref; status","§5.2"),
 ("DecisionContract","P15-A2","engine-now","Typed contract for one decision family defining input/result schema, subject kinds, evidence selectors, freshness, default behaviour, evaluator version.","decision_key; version; subject_kinds[]; input/result_schema_ref; required_evidence_selectors[]; freshness_policy; default_result; evaluator_ref/version; contract_digest","§4.1.1, §5.2"),
 ("PolicyDecision","P15-A2","engine-now","Reason-coded record every consequential action cites; indeterminate fails closed and is distinct from an authored deny.","decision_key; contract_digest; subject; input_digest; evidence_root_digest; policy_bundle_digest; result; reason_codes[]; explanation_ref?; decision_digest; trace_id","§5.2"),
 ("ToolContract","P15-A2","engine-now","Typed tool definition: effect class, idempotency/delivery/fence/replay semantics, limits, sensitivity, labels, enforcement profile.","tool_key; input/output_schema; effect_class; delivery_semantics; fence_support; replay_mode; authorization_action; limits; sensitivity_profile; allowed_input_labels[]; output_label_rules[]; enforcement_profile_ref; ambiguity_policy; status","§5.2"),
 ("RoleView","P15-A2","engine-now","Content-addressed least-privilege view: only the subjects/fields a role may observe + its tool allowlist + max information labels.","role; subject_refs[]; included/redacted_field_selectors[]; hidden_subject_classes[]; tool_contract_keys[]; maximum_information_labels[]; effective_policy_digest; view_digest","§5.2"),
 ("EnforcementProfile","P15-A2","engine-now","Concrete sandbox boundary a ToolContract compiles into, applied below the model.","filesystem_mounts[]; writable_paths[]; network_egress_rules[]; credential_scopes[]; process_and_syscall_policy; cpu_memory_pids_limits; output_limits; profile_digest","§5.2"),
 ("ObservedEffectSummary","P15-A2","seam-now","Declared-vs-observed runtime attestation of a tool invocation's actual reads/writes/network/processes.","tool_invocation_id; observed_*_digest; declared_vs_observed_verdict; attestation_ref","§5.2"),
 ("ActorIdentity","P15-A2","seam-now","Authenticated actor; local dev may use a local unsigned actor, team-server requires authenticated identity + role membership.","actor_id; actor_kind; display_name; auth_provider; verified_identity_ref?; roles[]; trust_domain_id; status","§5.2"),
 ("ActorAction","P15-A2","engine-now","Provenance record for every HumanDecision/approval/waiver/stop/amendment/grant-revocation/policy-activation/destructive-retention action.","actor_id; action_key; subject_ref; policy_decision_id; authority_root_digests[]; review_root_digest?; reason_ref?; trace_id; performed_at","§5.2"),
 ("ProviderContract","P15-A2","engine-now","Provider data-processing/retention/training/region/redaction posture governing egress.","provider_key; adapter_key; data_processing_class; retention_policy; training_use_policy; region_policy?; metadata_policy; supported_redaction_modes[]; max_input_sensitivity_labels[]; egress_attestation_requirements[]; contract_digest; status","§5.2"),
 ("ProviderEgressRecord","P15-A2","engine-now","Durable record of an external provider call; a call without a valid provider.egress PolicyDecision + this record is prohibited (distinct from RoleView visibility).","subject_ref; provider_contract_digest; role_view_digest; prompt_manifest_digest; input_label_summary; redaction_report_ref?; policy_decision_id; provider_request_id?; trace_id; sent_at","§5.2"),
 ("EffectAttempt","P15-A3","engine-now","Records an external call separately from its receipt so outcome_unknown isn't silently success/failure.","station_run_id; station_effect_id; fencing_token; admission_permit_id; idempotency_key; request_digest; started/completed_at?; status","§5.2"),
 ("EffectReceipt","P15-A3","engine-now","Durable receipt + reconciliation status for an external effect.","effect_attempt_id; fencing_token; idempotency_key; external_correlation_id?; request/result_digest; reconciliation_status; trace_id; observed_at","§5.2"),
 ("AuthorityEvent","P15-A3","engine-now","Low-volume transactional append-only audit/recovery record; shares one Postgres txn with its outbox notification.","event_id; stream_id; stream_version; event_type; subject_ref; causation_id?; correlation_id; trace_context; payload_ref; committed_at","§4.7, §5.2"),
 ("ObservationSegment","P15-A3","engine-now","High-volume transcript/tool-output/token/telemetry evidence in the ArtifactStore; never independently changes authority.","manifest_ref; sequence range; sensitivity; digest; storage pointer","§4.6"),
 ("ArtifactInput","P15-A3","engine-now","Queryable derivation edge: which artifact consumed which input, with role + invalidation policy.","consumer_artifact_id; input_subject_kind/id; input_digest; role(semantic/authority/evidence/advisory/presentation); invalidation_policy; created_at","§5.2, §8.3"),
 ("ArtifactAddress","P15-A3","engine-now","Separates content identity from storage addressing/auth so a plaintext digest can't leak existence across trust domains.","trust_domain_id; content_digest; ciphertext_digest?; opaque_storage_key; encryption_key_ref?; storage_backend","§5.8"),
 ("StationRunLeaseExt","P15-A3","reuse-extend","Lease/fencing extension to existing StationRun; every state mutation checks the current epoch.","lease_epoch; lease_owner_instance_id?; acquired/expires_at?; heartbeat_at?; trace_id","§5.2"),
 ("DependencyResolutionManifest","P15-A3","seam-now","Supply-chain resolution/hermeticity record; required verification may not rely on unlocked resolution without a waiver.","manifest_digest; repository_base_commit; package_manager; lockfile_digests[]; registry_mirror_policy; resolved_package_refs[]; script/network/cache/native policies; vulnerability_snapshot_ref?","§15.4"),
 ("EmergencyStopState","P15-A4","engine-now","Durable global/project stop state; at most one current row per scope, history as LedgerEvents.","scope; project_id?; status(clear/engaged); reason; actor; human_decision_id?; engaged/cleared_at?; trace_id","§5.2"),
 ("BudgetEnvelope","P15-A4","engine-now","Durable budget envelope per scope; the authoritative spend ceiling.","scope_kind/id; currency; token/cost/concurrency limits; rolling_window_ms?; policy_digest; status","§5.2"),
 ("BudgetReservation","P15-A4","engine-now","Transactional reservation taken before any costly provider/tool effect.","budget_envelope_id; subject; requested_tokens/cost?; reserved/expires_at; committed_actuals?; status; policy_decision_id; trace_id","§5.2"),
 ("AdapterHealthState","P15-A4","engine-now","Circuit state per adapter; opens on protocol/capability-drift/probe failures, not on coding-quality misses.","adapter; capability_snapshot_digest; state(closed/open/half_open); reason_codes[]; consecutive_failures; last_probe/success_at?; opened/next_probe_at?; affected_grant_ids[]","§5.2"),
 ("IncidentRecord","P15-B6","engine-now","Authority-bearing security-incident record; cannot be hidden by retention/projection while open.","incident_key; severity; incident_class; affected_subject/grant/artifact refs[]; containment_actions[]; evidence_refs[]; status; owner; opened/closed_at?","§12.6.1"),

 # ── §5.3 Phase-1.5 qualification resources ──
 ("PhaseNextDecision","P15-A0","engine-now","First durable artifact: records quantitative observations + selected branches from the retrospective + tracer.","phase0_1_report_ref; vertical_tracer_report_ref?; selected_branches[]; evidence_refs[]; decision_digest; status","§5.3"),
 ("CapabilityClaim","P15-B2","seam-now","Evidenced adapter capability (declared/probed/observed) with limits + freshness, not a bare boolean.","capability_key/version; mode_or_value; limits{}; source; evidence_ref; observed/expires_at?; known_degradations[]","§2.7"),
 ("EffectiveCapabilitySet","P15-B2","seam-now","Derived intersection of declaration/probes/observed/health/policy the conductor actually consumes.","adapter; declared/probe/observed_claim_refs[]; excluded_or_degraded_claims[]; effective_capabilities{}; derived/expires_at; capability_set_digest","§2.7"),
 ("SamplingPolicy","P15-B1","seam-now","Versioned content-addressed live sampling policy frozen before any provider call.","method; min/max_samples; confidence; floor_p0; stopping_rule; sampling_unit; cluster_key; max_samples_per_cluster; strata[]; sequential_validity","§2.4"),
 ("BatteryCase","P15-B1","engine-now","Role-safe case metadata; scorer-only trap/holdout/oracle metadata lives in the separate evaluation store.","case_id; case_kinds[]; criticality; archetype_key; repo_base_ref; role_safe_case_ref; policy_bundle_digest; sample_policy_ref?; trace_assertion_refs[]; labels[]; status","§5.3"),
 ("BatteryRun","P15-B1","engine-now","One exact corpus+policy+adapter/profile/environment invocation.","corpus/scoring_policy/requested_grant_scope digests; adapter; agent_profile_id; capability/environment digests; run_mode; prompt_template_version; trace_id; status; summary_ref; retention_class","§5.3"),
 ("BatterySampleResult","P15-B1","seam-now","One concrete sample + full trace-assertion results; quality_dimensions is a vector, not one rate; case_cluster_key bounds fixture contribution.","battery_run_id; battery_case_id; case_cluster_key; sample_no; run_attempt_ids[]; terminal_outcome; failure_classes[]; trace_assertion_results[]; forbidden_effect_count; first_pass/eventual_passed; quality_dimensions{}; cost/wall-clock; cassette_id?; status","§5.3"),
 ("BatteryCaseResult","P15-B1","engine-now","Aggregate over a predeclared sample set; never hides excluded samples.","battery_run_id; battery_case_id; sample_result_ids[]; sample_count; allowed_outcome_rate?; safety_violation_count; confidence_interval?; paired_regression_status?; release_verdict; notes","§5.3"),
 ("HumanReviewRubric","P15-B1","seam-now","Versioned rubric for subjective dimensions; frozen before sample review; disagreement preserved not averaged.","rubric_key/version; dimension; score_levels[]; anchor_examples_ref; reviewer_role_requirements; blinding_policy; minimum_reviewers; adjudication_policy; inter_rater_reliability_target?; rubric_digest","§5.3"),
 ("CassetteSeries","P15-B3","engine-now","Identifies the generation surface for a role/spec/adapter combination; one recording is never 'the' behaviour.","spec_kind; spec_digest; role; adapter; agent_profile/capability/generation-environment/freshness digests; created_at","§5.3"),
 ("AgentCassette","P15-B3","engine-now","One immutable recording; provider-identity confidence ladder; recorded gate results are diagnostic, never replay authority.","cassette_series_id; recording_no; provider_request_id?/model_id/revision?; provider_identity_confidence; agent_event_stream_ref; tool_transcript_ref; primary_output_refs[]; redaction_report_ref; seal_status; retention_class; recorded_at","§5.3"),
 ("NondeterminismLedger","P15-B3","seam-now","Records every clock/RNG/env/external-read/tool-equivalence dependency; an incomplete required ledger ⇒ replay_incomplete.","clock_reads[]; rng_seeds_or_recorded_values[]; environment_reads[]; external_read_versions[]; tool_equivalence_policy_versions[]; completeness","§2.9"),
 ("ReplayAnchorSet","P15-B3","engine-now","Policy-selected (before the evaluated change) representative recordings + exact expected replay assertions.","anchor_recording_refs[]; expected_assertions[]; selection_policy_digest; frozen_at","§2.9"),
 ("VerificationObligation","P15-B4","engine-now","Unit of authority; a TestPack is an evidence producer for one or more obligations.","slice_id; acceptance_ref; obligation_kind; required; oracle_definition_ref; evidence_requirement_ref; status","§5.3"),
 ("VerificationEvidence","P15-B4","engine-now","Multi-dimensional evidence item with validity.","verification_obligation_id; producer_kind/ref; evidence_kind; validity; environment_fingerprint_digest?; result_ref; evidence_digest; created_at","§5.3"),
 ("ObligationSatisfaction","P15-B4","engine-now","Deterministic result of evaluating every required evidence dimension; no generic 'stage at or above' rule.","verification_obligation_id; evidence_requirement_digest; consumed_evidence_ids[]; dimension_results{}; result; policy_decision_id; satisfaction_digest; evaluated_at","§5.3"),
 ("VerificationWaiver","P15-B4","engine-now","Scoped expiring waiver with owner + compensating controls + reduced autonomy; required obligation stays blocked otherwise.","verification_obligation_id; human_decision_id; reason; compensating_control_refs[]; max_autonomy; owner; expires_at; status","§5.3"),
 ("TestIntegrityRun","P15-B4","engine-now","Sentinel verdict across calibration/hermeticity/repeatability/oracle/mount/coverage axes.","test_pack_id; integrity_spec_digest; sample_no; slice_id; calibration; hermeticity; red_on_stub_or_falsifier; repeatability; interface_oracle_coverage; mount_integrity; obligation_coverage; overall; report_ref","§5.3"),
 ("TestQuarantine","P15-B4","engine-now","Isolates a suspect test but never marks an obligation satisfied.","test_pack_id; test_id; reason; required_for_obligation_ids[]; status; excluded_from; human_decision_id?; evidence_ref","§5.3"),
 ("BehaviorLockRun","P15-B5","engine-now","Fixture-scoped differential behaviour oracle; reports no_divergence_observed/diverged/inconclusive, not general equivalence.","run_attempt_id; slice_id; oracle_adapter; inputs_ref; baseline/candidate_output_ref; normalization_policy_ref; divergences[]; status","§5.3"),
 ("EvidenceComparison","P15-B6","engine-now","Typed multi-label comparison of any two subjects; missing/unauthorized/erased ⇒ incomparable.","project_id; left/right_subject_kind/id; comparison_ref/digest; materiality_labels[]; summary_status; created_by/at","§5.3"),
 ("FailureDiagnosis","P15-B6","engine-now","Immutable deterministic-first diagnosis with competing hypotheses + abstention.","subject; primary_classification; contributing_factors[]; observations[]; competing_hypotheses[]; confidence; confidence_basis; abstained; evidence_refs[]; rule_bundle_digest; diagnostic_version; diagnosis_digest","§5.3"),
 ("RecoveryProposal","P15-B6","engine-now","Typed recovery proposal: reusable/invalidated artifacts + new-spec/attempt + human/policy preconditions.","failure_diagnosis_id; action_key; arguments_ref; reusable/invalidated_artifact_refs[]; requires_new_spec/attempt/human; idempotent; precondition_policy_key; proposal_digest","§5.3"),
 ("RecoveryAction","P15-B6","engine-now","Separately authorized execution of a recovery proposal with effect receipts.","recovery_proposal_id; policy_decision_id; authorized_by?; station_run_id?; status; effect_receipt_refs[]","§5.3"),
 ("QualificationGrant","P15-B8","engine-now","Scoped, expiring, statistically-informed authority — immutable evidence about a scope, not a runtime lease.","project_id; qualification_gate_run_id; evidence_root_digest; scope_ref/digest; adapter/agent/archetype/change/toolchain/risk classes; policy/environment/deployment digests; max_autonomy; success_rate_bands[]; limitations[]; waiver_refs[]; issued/expires_at?; invalidation_triggers[]; status","§5.3"),
 ("QualificationScopeLattice","P15-B8","seam-now","Versioned scope lattice with direct/inherited/supporting evidence + worst-required-stratum; inheritance defaults to none.","direct_evidence_strata[]; inherited_evidence_strata[]; inheritance_rule_refs[]; unassessed_strata[]; worst_required_stratum_result","§2.8"),
 ("AdmissionPermit","P15-B8","engine-now","Short-lived current operational authority binding the immutable grant to current state for one effectful run.","subject_kind/id; spec_digest; qualification_grant_id; effective_capability_set_digest; authority_root_digests[]; policy/environment digests; budget_reservation_ids[]; control_generation; issued/expires_at; permit_digest; supersedes_permit_id?","§5.3"),
 ("PermitCheckpoint","P15-B8","engine-now","Revalidates admission at every effectful boundary of a long attempt; parks on a typed suspended/terminal reason.","admission_permit_id; subject_ref; station_run_id?; checkpoint_kind; validated_inputs_digest; result(valid/invalid/suspended); reason_codes[]; policy_decision_id; checked_at; trace_id","§5.3"),
 ("QualificationImpact","P15-B8","engine-now","Computes which grants/cases a proposed change affects + required requalification.","changed_subject_refs[]; changed_digest_classes[]; affected_grant_ids[]; required_requalification_case_ids[]; required_conformance_suite_refs[]; unaffected_evidence_refs[]; report_ref","§5.3"),
 ("ContextGroundTruth","P15-B7","seam-now","Battery-only labelled context truth enabling precision/recall; unlabelled work uses named proxies only.","case_id; necessary_source_refs[]; useful_source_refs[]; forbidden_or_irrelevant_source_refs[]; annotation_provenance","§16.9"),

 # ── §5.4 Phase-2 planning resources ──
 ("PlanSourceSnapshot","P2-A0","engine-now","Every imported plan byte; formatting-only changes create snapshots without a new semantic revision.","plan_id; source_document_ref; source_content_digest; imported_at/by","§5.4"),
 ("PlanRevision","P2-A0","engine-now","Immutable published semantic revision; workflow states live on PlanningRun, not here.","plan_id; revision_no; parent_revision_id?; source_snapshot_ids[]; normalized_contract_ref; contract_digest; change_class; status; created_by/at","§5.4"),
 ("ConstraintSet","P2-A0","engine-now","Validated hard/soft constraints with precedence + violation policy; PlanConstraint value object.","plan_revision_id; constraint_set_ref/digest; hard/soft counts; status; {key,kind,statement,strength,violation_policy,validation_kind,claim_ref}","§5.4, §6.5"),
 ("SourceAnchor","P2-A0","engine-now","Immutable-byte anchor (plan span / repo symbol / decision / artifact pointer / policy rule); line numbers alone aren't stable.","kind; source_blob_digest?; repository_commit?; path?; symbol_key?; byte/line ranges; excerpt_digest?; artifact_ref?; json_pointer?","§5.4, §6.2"),
 ("ClaimSet","P2-A0","engine-now","Provenance ledger keyed by JSON Pointer; compiler assigns deterministic provenance, model annotates only residual; subtree inheritance + ClaimCoverageReport.","subject; subject_content_digest; claims[{subject_pointer,origin,source_anchor_refs[],confidence,impact,inference_reason,approval_status}]; claim_set_digest","§5.4, §6.1"),
 ("PlanningSpec","P2-A0","engine-now","Immutable planning execution capsule: pass graph, budgets, RoleViews, environment, policies.","plan_revision_id; constraint_set_digest; qualification_grant_id; pass_graph_digest; policy_bundle_digest; prompt_template_versions; agent_profile_snapshots; repository_base_commit; environment_fingerprint_digest; planning_width; budgets; trace_id","§5.4"),
 ("PlanningRun","P2-A1","engine-now","Workflow/run state of a planning attempt (planned/running/clarification_needed/critic_rework/approval_ready/...).","plan_revision_id; planning_spec_id; attempt_no; status; outcome; failure_category?; started/completed_at?; trace_id","§5.4"),
 ("PlanInterrogation","P2-A1","engine-now","One deduplicated question batch per published revision; answers are HumanDecisions.","planning_run_id; plan_revision_id; interrogator_profile_id?; status; questions[]; question_batch_ref; created_at","§5.4"),
 ("DecompositionSelection","P2-A2","engine-now","Created only when policy produces >1 candidate; candidates remain artifacts and are never blended.","planning_run_id; candidate_set_ref/digest; selected_candidate_key; selection_actor; selection_rationale; comparison_ref; human_decision_id?","§5.4"),
 ("SliceDependency","P2-A3","engine-now","Work-graph edge only: execution_hard or integration_order; interface/decision/verification live in their own graphs.","plan_revision_id; predecessor/successor_slice_id; kind; rationale; source_anchor_refs[]; origin; confidence","§5.4"),
 ("InterfaceContract","P2-A3","engine-now","Provider/consumer compatibility contract with lock level; strict reserved for public/cross-Slice.","plan_revision_id; interface_key; kind; stability; lock_level; compatibility_policy; schema_ref?; owner_slice_id?; version; status","§5.4, §9.1"),
 ("SliceInterfaceBinding","P2-A3","engine-now","provides/requires/modifies binding; direction is not embedded in interface identity.","slice_id; interface_contract_id; direction; required_version_range?; compatibility_expectation; source_anchor_refs[]","§5.4"),
 ("SliceDecisionBlock","P2-A3","engine-now","A human decision blocks a Slice via its own graph, not a fake work edge.","slice_id; human_decision_id; reason; status","§5.4"),
 ("ContractAudit","P2-B2","engine-now","Dimensional contract-quality readiness report (never one opaque weighted number).","slice_id; agent_brief_id; test_pack_id?; planning_run_id; compiler_version; decision; stages[]; quality_dimensions; report_ref","§5.4, §9.5"),
 ("ChangeSet","P2-B5","seam-now","Canonical mutation algebra; preview and apply invoke the same pure reducer; base-root preconditions must still match.","subject; base_revision_digest; base_authority_root_digest?; operations[]; preconditions[]; materiality_labels[]; impact_preview_ref; resulting_revision_digest?; change_set_digest; status","§5.4"),
 ("PlanningBundle","P2-B4","engine-now","The approval bundle + manifest + layered roots; authority tree excludes the approval signature to avoid a circular digest.","planning_run_id; plan_revision_id; constraint_set_digest; qualification_grant_id; candidate_selection_id?; manifest_ref/digest; shared_authority_root_digest; epic_authority_root_digests[]; review_root_digest; archive_bundle_root_digest; projection_path/status","§5.4"),
 ("ApprovalPolicy","P2-B5","seam-now","Threshold/role/separation-of-duties policy; local dev uses threshold one.","policy_key/version; subject_scope; required_actor_roles[]; threshold; separation_of_duties_rules[]; required_acknowledgement_keys[]; expiry_policy; policy_digest","§5.4"),
 ("ApprovalSet","P2-B5","seam-now","The set of approvals binding to subject/review roots; quorum/SoD enforcement deferred.","subject_authority_roots[]; review_root_digest; approval_policy_digest; approval_ids[]; threshold_satisfied; active_revocation_events[]; approval_set_digest","§5.4"),
 ("PlanAmendmentProposal","P2-B6","engine-now","Material/nonmaterial amendment with full impact analysis from the derivation+interface graphs.","plan_id; base_plan_revision_id; dispute_kind; materiality; affected/downstream refs[]; invalidated_artifact_refs[]; impact_preview_ref; status; human_decision_id?; resulting_plan_revision_id?","§5.4"),
 ("ManualInterventionArtifact","P2-B6","engine-now","Typed honest manual-intervention intake (hidden manual reconstruction remains a release failure).","intervention_kind; subject_ref; base_authority_root_digest?; content_ref; actor_action_id; reason; affected_refs[]; materiality_labels[]; counts_as_generated_success; requires_reapproval","§11.1"),
 ("PilotSelection","P2-B7","engine-now","Immutable pre-registered pilot selection frozen before the first selected implementation attempt.","planning_bundle_id; selection_policy_digest; selected_slice_ids[]; required_coverage_classes[]; excluded_slice_ids_with_reasons[]; selection_digest; frozen_at","§5.4"),
]

BEADS = [s(*r) for r in R]
